import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Bed, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, Droplets, Dumbbell, Footprints, Gauge, Moon, Scale, Sparkles, Target, TrendingDown, TrendingUp, Utensils } from "lucide-react";
import { getCoachingClientProgress } from "@/lib/data";
import styles from "./client-progress.module.css";

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const isoDatePattern = /^\d{4}-\d{2}-\d{2}$/;
const dayNames = ["တနင်္ဂနွေ", "တနင်္လာ", "အင်္ဂါ", "ဗုဒ္ဓဟူး", "ကြာသပတေး", "သောကြာ", "စနေ"];
const numeric = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : null;
const displayDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
const shortDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", { day: "2-digit", month: "short", timeZone: "UTC" });
const dateFromTimestamp = (value: string) => new Date(value).toISOString().slice(0, 10);
const firstRelation = <T,>(value: T | T[] | null | undefined) => Array.isArray(value) ? value[0] ?? null : value ?? null;

function WeightChart({ rows }: { rows: Array<{ date: string; body_weight: unknown }> }) {
  const points = rows.filter((row) => numeric(row.body_weight) !== null).slice(0, 21).reverse().map((row) => ({ date: row.date, weight: numeric(row.body_weight) as number }));
  if (points.length < 2) return <div className={styles.empty}>Weight log နှစ်ရက်ပြည့်ရင် trend graph ပေါ်လာပါမယ်။</div>;
  const weights = points.map((point) => point.weight);
  const minimum = Math.min(...weights), maximum = Math.max(...weights), spread = Math.max(maximum - minimum, 1);
  const coordinates = points.map((point, index) => ({ ...point, x: 18 + (index / Math.max(points.length - 1, 1)) * 584, y: 18 + ((maximum - point.weight) / spread) * 124 }));
  const line = coordinates.map((point) => `${point.x},${point.y}`).join(" ");
  return <div className={styles.chartWrap}><svg aria-label={`Weight trend from ${points[0].weight} to ${points.at(-1)?.weight} kilograms`} role="img" viewBox="0 0 620 166"><defs><linearGradient id="weight-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#11add5" stopOpacity=".28"/><stop offset="1" stopColor="#11add5" stopOpacity="0"/></linearGradient></defs><line x1="18" x2="602" y1="150" y2="150"/><polygon fill="url(#weight-fill)" points={`18,150 ${line} 602,150`}/><polyline points={line}/>{coordinates.map((point) => <circle cx={point.x} cy={point.y} key={point.date} r="4"/>)}</svg><div className={styles.chartLabels}><span>{displayDate(points[0].date)}</span><strong>{minimum.toFixed(1)}–{maximum.toFixed(1)} kg</strong><span>{displayDate(points.at(-1)?.date ?? points[0].date)}</span></div></div>;
}

export default async function CoachingClientProgressPage({ params, searchParams }: { params: Promise<{ clientId: string }>; searchParams: Promise<{ date?: string }> }) {
  const [{ clientId }, query] = await Promise.all([params, searchParams]);
  if (!uuidPattern.test(clientId)) notFound();
  const client = await getCoachingClientProgress(clientId);
  if (!client) notFound();

  const currentWeightValue = numeric(client.trackers.find((row) => numeric(row.body_weight) !== null)?.body_weight);
  const startingWeight = numeric(client.bodyProfile?.starting_weight) ?? numeric(client.registration?.weight);
  const weightChange = currentWeightValue !== null && startingWeight !== null ? currentWeightValue - startingWeight : null;
  const completedWorkouts = client.workouts.filter((workout) => workout.completed).length;
  const workoutRate = client.workouts.length ? Math.round((completedWorkouts / client.workouts.length) * 100) : 0;
  const programStart = client.program?.start_date ? new Date(`${client.program.start_date}T00:00:00Z`) : null;
  const elapsedDays = programStart ? Math.max(0, Math.floor((new Date(client.generatedAt).getTime() - programStart.getTime()) / 86_400_000)) : 0;
  const currentWeek = client.program ? Math.min(client.program.duration_weeks, Math.floor(elapsedDays / 7) + 1) : null;
  const recentLogs = client.trackers.slice(0, 14);
  const habitChecks = recentLogs.flatMap((row) => [row.water_3l, row.omega_3, row.bed_phone_filter, row.meal_plan_adhered, row.toilet]);
  const habitRate = habitChecks.length ? Math.round((habitChecks.filter(Boolean).length / habitChecks.length) * 100) : 0;
  const averageSteps = recentLogs.length ? Math.round(recentLogs.reduce((sum, row) => sum + (numeric(row.steps) ?? 0), 0) / recentLogs.length) : 0;
  const sleepValues = recentLogs.map((row) => numeric(row.sleep_score)).filter((value): value is number => value !== null);
  const averageSleep = sleepValues.length ? (sleepValues.reduce((sum, value) => sum + value, 0) / sleepValues.length).toFixed(1) : "—";

  const dayDates = [...new Set([...client.trackers.map((row) => row.date), ...client.workouts.map((row) => row.date), ...client.journals.map((row) => row.date), ...client.nutritionLogs.map((row) => row.date), ...client.checkins.map((row) => dateFromTimestamp(row.created_at))])].sort((a, b) => b.localeCompare(a));
  const selectedDate = query.date && isoDatePattern.test(query.date) && dayDates.includes(query.date) ? query.date : dayDates[0] ?? new Date(client.generatedAt).toISOString().slice(0, 10);
  const selectedIndex = dayDates.indexOf(selectedDate);
  const selectedTracker = client.trackers.find((row) => row.date === selectedDate) ?? null;
  const selectedWorkouts = client.workouts.filter((row) => row.date === selectedDate);
  const selectedJournal = client.journals.find((row) => row.date === selectedDate) ?? null;
  const selectedNutrition = client.nutritionLogs.filter((row) => row.date === selectedDate);
  const selectedCheckins = client.checkins.filter((row) => dateFromTimestamp(row.created_at) === selectedDate);
  const selectedDayOfWeek = new Date(`${selectedDate}T00:00:00Z`).getUTCDay();
  const scheduledDay = client.schedule.find((row) => row.day_of_week === selectedDayOfWeek) ?? null;
  const trackerValues = selectedTracker?.tracker_values && typeof selectedTracker.tracker_values === "object" && !Array.isArray(selectedTracker.tracker_values) ? selectedTracker.tracker_values as Record<string, unknown> : {};
  const selectedHabitCount = selectedTracker ? [selectedTracker.water_3l, selectedTracker.omega_3, selectedTracker.bed_phone_filter, selectedTracker.meal_plan_adhered, selectedTracker.toilet].filter(Boolean).length : 0;
  const selectedRecordCount = Number(Boolean(selectedTracker)) + selectedWorkouts.length + selectedNutrition.length + Number(Boolean(selectedJournal)) + selectedCheckins.length;
  const templateSections = Array.isArray(client.template?.sections) ? client.template.sections as Array<{ title?: string; fields?: Array<{ id?: string; label?: string; type?: string }> }> : [];
  const templateFieldCount = templateSections.reduce((total, section) => total + (section.fields?.length ?? 0), 0);
  const progressPhotos = client.checkins.filter((checkin) => checkin.progressPhotoUrl);
  const baselinePhotos = client.registration ? Object.entries(client.registration.photos).filter((entry): entry is [string, string] => Boolean(entry[1])) : [];

  return <div className={styles.page}>
    <Link className={styles.back} href="/coaching/clients"><ArrowLeft size={16}/>1:1 Clients ပြန်သွားမယ်</Link>
    <header className={styles.hero}><div className={styles.identity}><span className={styles.avatar}>{(client.profile.username || client.profile.email || "P").slice(0, 1).toUpperCase()}</span><div><p>CLIENT PROGRESS · LIVE</p><h1>{client.profile.username || client.registration?.name || "1:1 Client"}</h1><span>{client.profile.email}</span></div></div><div className={styles.heroStatus}><span>{client.registration?.payment_status === "ready" ? "PLAN ACTIVE" : (client.registration?.payment_status ?? "pending").toUpperCase()}</span><strong>{client.program ? `Week ${currentWeek} / ${client.program.duration_weeks}` : "Program မသတ်မှတ်ရသေး"}</strong><small>{client.program ? `${displayDate(client.program.start_date)} မှ စတင်` : "Template မစတင်ရသေးပါ"}</small></div></header>

    <section className={styles.metrics} aria-label="Client progress summary">
      <article><span><Scale size={17}/></span><small>လက်ရှိ Weight</small><strong>{currentWeightValue !== null ? `${currentWeightValue.toFixed(1)} kg` : "—"}</strong><p>{weightChange !== null ? <>{weightChange <= 0 ? <TrendingDown size={14}/> : <TrendingUp size={14}/>}စမှတ်ထက် {Math.abs(weightChange).toFixed(1)} kg {weightChange <= 0 ? "လျော့" : "တိုး"}</> : "Starting weight မရှိသေး"}</p></article>
      <article><span><Dumbbell size={17}/></span><small>Workout ပြီးစီးမှု</small><strong>{workoutRate}%</strong><p>{completedWorkouts} / {client.workouts.length} sessions</p></article>
      <article><span><Gauge size={17}/></span><small>Habit Consistency</small><strong>{habitRate}%</strong><p>နောက်ဆုံး {recentLogs.length} logs</p></article>
      <article><span><ClipboardCheck size={17}/></span><small>Weekly Check-ins</small><strong>{client.checkins.length}</strong><p>{client.checkins[0] ? `နောက်ဆုံး Week ${client.checkins[0].week_number}` : "မဖြည့်ရသေး"}</p></article>
    </section>

    <section className={styles.dayBrowser} id="day-detail">
      <aside className={styles.dayRail}><div className={styles.dayRailHead}><div><p>DAY BY DAY</p><h2>ရက်ရွေးကြည့်မယ်</h2></div><CalendarDays size={19}/></div><nav aria-label="Client activity dates">{dayDates.slice(0, 45).map((date) => { const tracker = client.trackers.some((row) => row.date === date), workout = client.workouts.some((row) => row.date === date), meals = client.nutritionLogs.some((row) => row.date === date); return <Link data-active={date === selectedDate} href={`/coaching/clients/${clientId}?date=${date}#day-detail`} key={date} prefetch={false}><span><strong>{shortDate(date)}</strong><small>{dayNames[new Date(`${date}T00:00:00Z`).getUTCDay()]}</small></span><i>{tracker ? <span title="Tracker"/> : null}{workout ? <span title="Workout"/> : null}{meals ? <span title="Meals"/> : null}</i><ChevronRight size={15}/></Link>; })}</nav></aside>
      <div className={styles.dayContent}>
        <header className={styles.dayHero}><div><p>SELECTED DAY</p><h2>{displayDate(selectedDate)}</h2><span>{dayNames[selectedDayOfWeek]} · {selectedRecordCount ? `${selectedRecordCount} records` : "မှတ်တမ်းမရှိသေး"}</span></div><div className={styles.dayNav}>{selectedIndex > 0 ? <Link aria-label="Newer day" href={`/coaching/clients/${clientId}?date=${dayDates[selectedIndex - 1]}#day-detail`}><ChevronLeft size={17}/></Link> : <span/>}{selectedIndex >= 0 && selectedIndex < dayDates.length - 1 ? <Link aria-label="Older day" href={`/coaching/clients/${clientId}?date=${dayDates[selectedIndex + 1]}#day-detail`}><ChevronRight size={17}/></Link> : <span/>}</div></header>
        <div className={styles.dayModules}>
          <article className={styles.dayModule}><ModuleHead icon={<Gauge size={17}/>} eyebrow="TRACKER" title="နေ့စဉ်အခြေအနေ" badge={selectedTracker ? `${selectedHabitCount}/5 habits` : undefined}/>{selectedTracker ? <><dl className={styles.facts}><Fact label="Weight" value={numeric(selectedTracker.body_weight) !== null ? `${numeric(selectedTracker.body_weight)?.toFixed(1)} kg` : "—"}/><Fact label="Steps" value={numeric(selectedTracker.steps)?.toLocaleString() ?? "—"}/><Fact label="Water" value={numeric(selectedTracker.water_liters) !== null ? `${numeric(selectedTracker.water_liters)} L` : selectedTracker.water_3l ? "Done" : "—"}/><Fact label="Sleep" value={numeric(selectedTracker.sleep_score) !== null ? `${numeric(selectedTracker.sleep_score)}/10` : String(trackerValues.sleep || "—")}/><Fact label="Wake" value={selectedTracker.wake_time || "—"}/><Fact label="Phone off" value={selectedTracker.phone_off_time || "—"}/></dl>{selectedTracker.one_win || trackerValues.win ? <DayNote positive title="ဒီနေ့အောင်မြင်မှု" text={String(selectedTracker.one_win || trackerValues.win)}/> : null}{selectedTracker.one_struggle ? <DayNote title="အခက်အခဲ" text={selectedTracker.one_struggle}/> : null}</> : <Empty icon={<Gauge size={24}/>} title="Tracker မဖြည့်ရသေးပါ" text="Client ဖြည့်ပြီးရင် ဒီနေ့အချက်အလက် ဒီမှာပေါ်ပါမယ်။"/>}</article>
          <article className={styles.dayModule}><ModuleHead icon={<Dumbbell size={17}/>} eyebrow="WORKOUT" title="Session Detail"/>{selectedWorkouts.length ? <div className={styles.workoutList}>{selectedWorkouts.map((workout) => <section key={workout.id}><header><div><strong>{workout.split_name}</strong><small>{workout.exercises.length} exercises · {workout.user_feelings || "Feeling မမှတ်ထား"}</small></div><b data-complete={workout.completed}>{workout.completed ? "DONE" : "PLANNED"}</b></header>{workout.exercises.length ? <div className={styles.exerciseList}>{workout.exercises.map((exercise, index) => <div key={exercise.id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{exercise.exercise_name}</strong><small>{exercise.target_sets} sets · {exercise.target_reps} reps</small></div><b>{exercise.actual_weight || "—"}<small>{exercise.actual_reps || "No log"}</small></b></div>)}</div> : <div className={styles.subEmpty}>Exercise မထည့်ရသေးပါ</div>}{workout.user_notes ? <DayNote title="Client note" text={workout.user_notes}/> : null}</section>)}</div> : scheduledDay?.is_rest ? <State icon={<Moon size={28}/>} title="Recovery Day" text="ဒီနေ့က schedule အရ Rest Day ဖြစ်ပါတယ်။ Workout မလိုပါ။" rest/> : <State icon={<Dumbbell size={28}/>} title="Session ပြင်ဆင်နေဆဲ" text={scheduledDay?.split_name ? `${scheduledDay.split_name} session ကို coach က exercise ထည့်ပေးဖို့လိုပါတယ်။` : "ဒီနေ့အတွက် schedule သို့မဟုတ် workout မသတ်မှတ်ရသေးပါ။"}/>}</article>
          <article className={styles.dayModule}><ModuleHead icon={<Utensils size={17}/>} eyebrow="MEALS" title="Nutrition" badge={selectedNutrition.length ? `${selectedNutrition.filter((row) => row.completed).length}/${selectedNutrition.length}` : undefined}/>{selectedNutrition.length ? <div className={styles.meals}>{selectedNutrition.map((log) => { const item = firstRelation(log.coaching_nutrition_items); return <div data-complete={log.completed} key={log.id}><CheckCircle2 size={16}/><span><strong>{item?.food_name_mm || item?.food_name || "Meal item"}</strong><small>{item?.meal_type || "Meal"} · {item?.portion || "portion မရှိသေး"}</small></span><b>{item?.calories ?? 0} kcal</b></div>; })}</div> : <Empty icon={<Utensils size={24}/>} title="Meal log မရှိသေးပါ" text="Client ရွေးပြီးစားထားတဲ့ meal တွေ ဒီမှာပေါ်ပါမယ်။"/>}</article>
          <article className={styles.dayModule}><ModuleHead icon={<Sparkles size={17}/>} eyebrow="DAY NOTE" title="နေ့တာသုံးသပ်ချက်"/>{selectedJournal ? <div className={styles.journal}><Journal label="Diet status" value={selectedJournal.diet_status}/><Journal label="ကျေနပ်ခဲ့တာ" value={selectedJournal.satisfied_with}/><Journal label="ခက်ခဲခဲ့တာ" value={selectedJournal.difficult_with}/></div> : <Empty icon={<Sparkles size={24}/>} title="နေ့တာ note မရှိသေးပါ" text="Client ရေးထားတဲ့ reflection ကို ဒီမှာကြည့်နိုင်ပါတယ်။"/>}</article>
        </div>
        {selectedCheckins.length ? <section className={styles.dayCheckin}><ModuleHead icon={<ClipboardCheck size={17}/>} eyebrow="WEEKLY CHECK-IN" title="ဒီနေ့တင်ထားတဲ့ Review"/>{selectedCheckins.map((checkin) => <div className={styles.checkinBody} key={checkin.id}><dl><Fact label="Week" value={String(checkin.week_number)}/><Fact label="Weight" value={`${numeric(checkin.avg_weight)?.toFixed(1) ?? "—"} kg`}/><Fact label="Motivation" value={`${checkin.motivation ?? "—"}/10`}/></dl>{checkin.improvement_notes ? <DayNote positive title="တိုးတက်မှု" text={checkin.improvement_notes}/> : null}{checkin.struggle_notes ? <DayNote title="အခက်အခဲ" text={checkin.struggle_notes}/> : null}{checkin.admin_feedback ? <blockquote><strong>Coach feedback</strong>{checkin.admin_feedback}</blockquote> : null}</div>)}</section> : null}
      </div>
    </section>

    <div className={styles.overviewGrid}><section className={styles.card}><CardHead eyebrow="WEIGHT TREND" title="အပြောင်းအလဲ Overview" icon={<Scale size={20}/>}/><WeightChart rows={client.trackers}/></section><section className={styles.card}><CardHead eyebrow="LAST 14 LOGS" title="Consistency Overview" icon={<Sparkles size={20}/>}/><div className={styles.quickStats}><div><Footprints size={16}/><span>Average steps</span><strong>{averageSteps.toLocaleString()}</strong></div><div><Bed size={16}/><span>Average sleep</span><strong>{averageSleep}</strong></div><div><Droplets size={16}/><span>Habit score</span><strong>{habitRate}%</strong></div></div></section></div>
    <details className={styles.archive}><summary><span><ClipboardCheck size={18}/><strong>Weekly check-in အားလုံး</strong><small>{client.checkins.length} reviews</small></span><ChevronRight size={18}/></summary><div className={styles.checkinArchive}>{client.checkins.map((checkin) => <article key={checkin.id}><span>W{String(checkin.week_number).padStart(2, "0")}</span><div><strong>{numeric(checkin.avg_weight)?.toFixed(1) ?? "—"} kg · Motivation {checkin.motivation ?? "—"}/10</strong><small>{new Date(checkin.created_at).toLocaleDateString("en-GB")}</small><p>{checkin.admin_feedback || checkin.improvement_notes || "Feedback မရှိသေးပါ"}</p></div></article>)}</div></details>
    <details className={styles.archive}><summary><span><Target size={18}/><strong>Client plan နှင့် template</strong><small>{client.template?.name || "Template မရှိသေး"}</small></span><ChevronRight size={18}/></summary><div className={styles.planGrid}><section><h3>Program</h3><dl className={styles.profileFacts}><Fact label="Program" value={client.registration?.program_name || client.program?.program_type || "—"}/><Fact label="Height" value={client.bodyProfile?.height_cm ? `${client.bodyProfile.height_cm} cm` : client.registration?.height || "—"}/><Fact label="Starting weight" value={startingWeight !== null ? `${startingWeight} kg` : "—"}/><Fact label="Goal" value={client.bodyProfile?.desired_body_text || "—"}/></dl></section><section><h3>{client.template?.name || "Custom template"}</h3><p className={styles.templateCount}>{templateSections.length} sections · {templateFieldCount} fields</p><div className={styles.templateSections}>{templateSections.map((section, index) => <article key={`${section.title}-${index}`}><span>0{index + 1}</span><div><strong>{section.title || `Section ${index + 1}`}</strong><small>{(section.fields ?? []).map((field) => field.label).filter(Boolean).join(" · ")}</small></div></article>)}</div></section></div></details>
    {baselinePhotos.length || progressPhotos.length ? <details className={styles.archive}><summary><span><Sparkles size={18}/><strong>Body progress photos</strong><small>{baselinePhotos.length + progressPhotos.length} photos</small></span><ChevronRight size={18}/></summary><div className={styles.photos}>{baselinePhotos.map(([slot, url]) => <figure key={slot}><Image alt={`${slot} baseline`} height={480} src={url} unoptimized width={360}/><figcaption>Baseline · {slot}</figcaption></figure>)}{progressPhotos.map((checkin) => <figure key={checkin.id}><Image alt={`Week ${checkin.week_number} progress`} height={480} src={checkin.progressPhotoUrl as string} unoptimized width={360}/><figcaption>Week {checkin.week_number} progress</figcaption></figure>)}</div></details> : null}
  </div>;
}

function ModuleHead({ icon, eyebrow, title, badge }: { icon: React.ReactNode; eyebrow: string; title: string; badge?: string }) { return <div className={styles.moduleHead}><span>{icon}</span><div><p>{eyebrow}</p><h3>{title}</h3></div>{badge ? <b>{badge}</b> : null}</div>; }
function CardHead({ icon, eyebrow, title }: { icon: React.ReactNode; eyebrow: string; title: string }) { return <div className={styles.cardHead}><div><p>{eyebrow}</p><h2>{title}</h2></div>{icon}</div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function DayNote({ title, text, positive = false }: { title: string; text: string; positive?: boolean }) { return <p className={positive ? styles.positive : styles.note}>{positive ? <CheckCircle2 size={14}/> : null}<span><strong>{title}</strong>{text}</span></p>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className={styles.moduleEmpty}>{icon}<strong>{title}</strong><span>{text}</span></div>; }
function State({ icon, title, text, rest = false }: { icon: React.ReactNode; title: string; text: string; rest?: boolean }) { return <div className={rest ? styles.restState : styles.preparingState}>{icon}<strong>{title}</strong><span>{text}</span></div>; }
function Journal({ label, value }: { label: string; value: string | null }) { return <div><strong>{label}</strong><p>{value || "—"}</p></div>; }
