"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Dumbbell, Pencil, Play, Plus, Save, Upload, Video } from "lucide-react";
import { saveCoachingExerciseLibraryItem } from "@/app/coaching-actions";
import styles from "./content-managers.module.css";

type Exercise={id:number;program_type:string;split_name:string;exercise_name:string;muscle_group:string|null;sets_default:number|null;reps_default:string|null;rest_seconds:number|null;form_video_url:string|null;sort_order:number|null};
type Form={id?:number;programType:string;splitName:string;exerciseName:string;muscleGroup:string;setsDefault:number;repsDefault:string;restSeconds:number;sortOrder:number};
const blank=():Form=>({programType:"personal_coaching",splitName:"Full Body",exerciseName:"",muscleGroup:"",setsDefault:3,repsDefault:"8-12",restSeconds:90,sortOrder:0});

export function ExerciseLibraryManager({items}:{items:Exercise[]}){
 const router=useRouter();const [form,setForm]=useState<Form>(blank);const [query,setQuery]=useState("");const [split,setSplit]=useState("all");const [message,setMessage]=useState("");const [ok,setOk]=useState(false);const [pending,startTransition]=useTransition();const [uploading,setUploading]=useState<number|null>(null);const [activeVideo,setActiveVideo]=useState<number|null>(null);
 const splits=useMemo(()=>[...new Set(items.map(item=>item.split_name))],[items]);
 const visible=useMemo(()=>items.filter(item=>(split==="all"||item.split_name===split)&&(!query.trim()||`${item.exercise_name} ${item.muscle_group||""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))),[items,query,split]);
 function edit(item:Exercise){setForm({id:item.id,programType:item.program_type,splitName:item.split_name,exerciseName:item.exercise_name,muscleGroup:item.muscle_group||"",setsDefault:item.sets_default||3,repsDefault:item.reps_default||"8-12",restSeconds:item.rest_seconds??90,sortOrder:item.sort_order||0});setMessage("");window.scrollTo({top:0,behavior:"smooth"});}
 function save(){startTransition(async()=>{const result=await saveCoachingExerciseLibraryItem(form);setOk(result.ok);setMessage(result.message);if(result.ok&&result.exerciseId){setForm(value=>({...value,id:result.exerciseId}));router.refresh();}});}
 async function uploadVideo(exerciseId:number,file?:File){if(!file)return;setUploading(exerciseId);setMessage("");try{const body=new FormData();body.set("intent","coaching-exercise");body.set("exerciseId",String(exerciseId));body.set("file",file);const response=await fetch("/api/admin/upload",{method:"POST",body});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Video upload မအောင်မြင်ပါ");setOk(true);setMessage("Exercise video တင်ပြီး database နဲ့ချိတ်ပြီးပါပြီ။");setActiveVideo(exerciseId);router.refresh();}catch(error){setOk(false);setMessage(error instanceof Error?error.message:"Video upload မအောင်မြင်ပါ");}finally{setUploading(null);}}
 return <div className={styles.page}><header className={styles.hero}><div><p>1:1 COACHING · EXERCISE LIBRARY</p><h1>Exercise + Video တစ်နေရာထဲ</h1><span>Exercise ကို Library ထဲတစ်ခါထည့်ပြီး Workout ဆောက်တဲ့အခါ dropdown ကနေပြန်ရွေးပါ။ Form video ကို exercise တစ်ခုစီမှာ သီးသန့်တင်နိုင်ပါတယ်။</span></div>{message?<div className={styles.status} data-ok={ok}>{message}</div>:null}</header>
 <section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}>{form.id?"EDIT EXERCISE":"NEW EXERCISE"}</p><h2>{form.id?form.exerciseName:"Library ထဲထည့်မယ်"}</h2></div><button className={styles.secondary} onClick={()=>{setForm(blank());setMessage("");}}><Plus size={16}/>အသစ်</button></div><div className={styles.panelBody}><div className={styles.row}><label className={styles.field}><span>Exercise နာမည် *</span><input value={form.exerciseName} onChange={e=>setForm({...form,exerciseName:e.target.value})} placeholder="ဥပမာ Dumbbell bench press"/></label><label className={styles.field}><span>Split *</span><input value={form.splitName} onChange={e=>setForm({...form,splitName:e.target.value})} placeholder="ဥပမာ Push A"/></label></div><div className={styles.row}><label className={styles.field}><span>Muscle group</span><input value={form.muscleGroup} onChange={e=>setForm({...form,muscleGroup:e.target.value})} placeholder="Chest"/></label><label className={styles.field}><span>Reps</span><input value={form.repsDefault} onChange={e=>setForm({...form,repsDefault:e.target.value})} placeholder="8-12"/></label></div><div className={styles.row}><label className={styles.field}><span>Sets</span><input type="number" min="1" max="20" value={form.setsDefault} onChange={e=>setForm({...form,setsDefault:Number(e.target.value)})}/></label><label className={styles.field}><span>Rest seconds</span><input type="number" min="0" max="3600" value={form.restSeconds} onChange={e=>setForm({...form,restSeconds:Number(e.target.value)})}/></label></div><div className={styles.actions}><Link className={styles.link} href="/coaching/workouts">Workout ဆောက်မယ့်နေရာ →</Link><button className={styles.button} disabled={pending||!form.exerciseName.trim()||!form.splitName.trim()} onClick={save}><Save size={16}/>{pending?"သိမ်းနေတယ်…":"Exercise သိမ်းမယ်"}</button></div></div></section>
 <section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}>VIDEO MANAGER</p><h2>Exercise Videos</h2></div><span>{visible.length} / {items.length}</span></div><div className={styles.panelBody}><div className={styles.libraryTools}><label className={styles.field}><span>Exercise ရှာမယ်</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Exercise name ရိုက်ရှာပါ"/></label><label className={styles.field}><span>Split</span><select value={split} onChange={e=>setSplit(e.target.value)}><option value="all">အားလုံး</option>{splits.map(value=><option key={value}>{value}</option>)}</select></label></div><div className={styles.libraryGrid}>{visible.length?visible.map(item=><article className={styles.exerciseCard} key={item.id}><header className={styles.exerciseCardHead}><div><h3>{item.exercise_name}</h3><p>{item.split_name} · {item.muscle_group||"Muscle group မသတ်မှတ်ရသေး"}</p></div><button className={styles.iconButton} onClick={()=>edit(item)} aria-label={`${item.exercise_name} ပြင်မယ်`}><Pencil size={16}/></button></header><div className={styles.libraryMeta}><span>{item.sets_default||3} sets</span><span>{item.reps_default||"8-12"} reps</span><span>{item.rest_seconds??90}s rest</span></div><div className={styles.videoArea}>{item.form_video_url?activeVideo===item.id?<video controls playsInline preload="metadata" src={item.form_video_url}/>:<button className={styles.videoPlay} onClick={()=>setActiveVideo(item.id)}><i><Play fill="currentColor" size={18}/></i><strong>Video ကြည့်မယ်</strong><small>နှိပ်မှ load လုပ်ပါမယ်</small></button>:<div className={styles.videoPlaceholder}><Video size={26}/><strong>Video မရှိသေးပါ</strong><span>MP4, WebM, MOV · 75MB အောက်</span></div>}</div>{uploading===item.id?<div className={styles.progressLine}><span/></div>:null}<footer className={styles.videoFoot}><span>{item.form_video_url?"Video ထည့်ပြီး":"Form video တင်ရန်"}</span><label className={styles.uploadButton}>{uploading===item.id?<Dumbbell size={15}/>:<Upload size={15}/>} {uploading===item.id?"တင်နေတယ်…":item.form_video_url?"Video ပြောင်းမယ်":"Video တင်မယ်"}<input type="file" accept="video/mp4,video/webm,video/quicktime" disabled={uploading!==null} onChange={e=>void uploadVideo(item.id,e.target.files?.[0])}/></label></footer></article>):<div className={styles.empty}>Exercise မရှိသေးပါ။ အပေါ်က form နဲ့ အသစ်ထည့်ပါ။</div>}</div></div></section></div>;
}
