"use client";

import { useState, useTransition } from "react";
import { Save } from "lucide-react";
import { saveCoachingFeedbackTemplate } from "@/app/coaching-actions";
import styles from "./content-managers.module.css";

type Key="avg_weight"|"progress_photo"|"energy_workout"|"energy_daily"|"motivation"|"struggle_notes"|"improvement_notes"|"upcoming_disruptions"|"changes_wanted";
type Field={key:Key;label:string;type:"number"|"image"|"rating"|"text"};
type Template={id:number;name:string;cadence:string;fields:unknown;active:boolean};
const defaults:Field[]=[
 {key:"avg_weight",label:"ဒီအပတ် ပျမ်းမျှကိုယ်အလေးချိန်",type:"number"},{key:"progress_photo",label:"Progress photo",type:"image"},{key:"energy_workout",label:"Workout လုပ်ချိန် Energy",type:"rating"},{key:"energy_daily",label:"တစ်နေ့တာ Energy",type:"rating"},{key:"motivation",label:"Motivation level",type:"rating"},{key:"struggle_notes",label:"ဒီအပတ် အဓိကအခက်အခဲ",type:"text"},{key:"improvement_notes",label:"ဒီအပတ် တိုးတက်မှု / အနိုင်ရမှု",type:"text"},{key:"upcoming_disruptions",label:"လာမယ့်အပတ် ထိခိုက်နိုင်မယ့်ကိစ္စ",type:"text"},{key:"changes_wanted",label:"Food / Exercise ပြောင်းချင်တာ",type:"text"},
];
function normalize(value:unknown):Field[]{if(!Array.isArray(value))return defaults;const source=value as Array<Record<string,unknown>>;return defaults.map((fallback,index)=>{const byKey=source.find(row=>row.key===fallback.key)??source[index];return {...fallback,label:typeof byKey?.label==="string"&&byKey.label.trim()?byKey.label:fallback.label};});}
export function FeedbackFormManager({templates}:{templates:Template[]}){
 const first=templates.find(t=>t.cadence==="weekly")??templates[0];const [id,setId]=useState<number|undefined>(first?.id);const [name,setName]=useState(first?.name||"Weekly Coaching Check-in");const [cadence,setCadence]=useState<"weekly"|"end">(first?.cadence==="end"?"end":"weekly");const [active,setActive]=useState(first?.active??true);const [fields,setFields]=useState<Field[]>(normalize(first?.fields));const [message,setMessage]=useState("");const [ok,setOk]=useState(false);const [pending,startTransition]=useTransition();
 function choose(value:string){const template=templates.find(t=>String(t.id)===value);if(!template)return;setId(template.id);setName(template.name);setCadence(template.cadence==="end"?"end":"weekly");setActive(template.active);setFields(normalize(template.fields));setMessage("");}
 function save(){startTransition(async()=>{const result=await saveCoachingFeedbackTemplate({id,name,cadence,active,fields});setOk(result.ok);setMessage(result.message);if(result.ok&&result.templateId)setId(result.templateId);});}
 return <div className={styles.page}><header className={styles.hero}><div><p>1:1 COACHING · FEEDBACK</p><h1>Check-in မေးခွန်းတွေ ပြင်မယ်</h1><span>Client ဖတ်ရမယ့် မေးခွန်းစာသားတွေကို ဒီမှာပဲ ပြင်နိုင်ပါတယ်။ Data အမျိုးအစားနဲ့ save ဖြစ်မယ့်နေရာကို system က ထိန်းထားလို့ မှားဖျက်မိစရာမရှိပါဘူး။</span></div>{message?<div className={styles.status} data-ok={ok}>{message}</div>:null}</header><div className={styles.layout}><aside className={styles.panel}><div className={styles.panelHead}><h2>Form Settings</h2></div><div className={styles.panelBody}>{templates.length?<label className={styles.field}><span>ပြင်မယ့် Form</span><select value={id} onChange={e=>choose(e.target.value)}>{templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>:null}<label className={styles.field}><span>Form နာမည်</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className={styles.field}><span>ဘယ်အချိန်ဖြည့်မလဲ?</span><select value={cadence} onChange={e=>setCadence(e.target.value as "weekly"|"end")}><option value="weekly">အပတ်စဉ်</option><option value="end">Program အဆုံး</option></select></label><label className={styles.toggle}><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span>ဒီ Form ကို အသုံးပြုမယ်</span></label><div className={styles.help}><strong>ရိုးရှင်းအောင် lock ထားတာ</strong><br/>Weight၊ photo၊ rating နဲ့ note တွေရဲ့ database mapping ကို မဖျက်မိအောင် type ကို system က ထိန်းထားပါတယ်။ စာသားကိုတော့ စိတ်ကြိုက်ပြင်နိုင်ပါတယ်။</div></div></aside><section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}>CLIENT WILL SEE</p><h2>မေးခွန်းစာသား</h2></div><span>{fields.length} ခု</span></div><div className={styles.panelBody}><div className={styles.questionList}>{fields.map((field,index)=><label className={styles.question} key={field.key}><span>{String(index+1).padStart(2,"0")}</span><input value={field.label} onChange={e=>setFields(rows=>rows.map((row,i)=>i===index?{...row,label:e.target.value}:row))}/><small>{field.type==="rating"?"1–10 rating":field.type}</small></label>)}</div><div className={styles.actions}><span/><button className={styles.button} disabled={pending||!name.trim()||fields.some(field=>!field.label.trim())} onClick={save}><Save size={17}/>{pending?"သိမ်းနေတယ်…":"Feedback Form သိမ်းမယ်"}</button></div></div></section></div></div>;
}
