import { ExternalLink } from "lucide-react";
import { reviewCoachingPayment } from "@/app/coaching-actions";
import { getCoachingPayments } from "@/lib/data";
import styles from "@/components/admin/admin.module.css";

export default async function CoachingPaymentsPage() {
  const rows = await getCoachingPayments();
  const pending = rows.filter((row)=>row.payment_status==="pending").length;
  return <><div className={styles.pageHeader}><div><p className={styles.eyebrow}>{pending} ခု စစ်ဆေးဖို့ကျန်</p><h1 className={styles.pageTitle}>1:1 Payment စစ်မယ်</h1><p className={styles.pageDescription}>Website ကတင်ထားတဲ့ receipt ကိုကြည့်ပြီး 550,000 MMK မှန်ရင် Approve လုပ်ပါ။ Approve ပြီးမှ client အတွက် custom template ဆောက်လို့ရပါမယ်။</p></div></div><section className={styles.panel}><div className={styles.panelHeader}><h2>Payment အားလုံး</h2><span className={styles.muted}>{rows.length} ခု</span></div>{rows.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Client</th><th>Package</th><th>Amount</th><th>Receipt</th><th>Status</th><th>လုပ်ဆောင်ရန်</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td data-label="Client"><strong>{row.name||"Google Client"}</strong><small className="mono">{row.email||"—"}</small></td><td data-label="Package"><strong>{row.program_name||"1:1 Coaching"}</strong><small>{row.duration_months} months</small></td><td data-label="Amount" className="mono">{Number(row.program_price||550000).toLocaleString()} MMK</td><td data-label="Receipt">{row.payment_url?<a className={styles.buttonSecondary} href={row.payment_url} target="_blank" rel="noreferrer">ပုံကြည့်မယ် <ExternalLink size={13}/></a>:<span className={styles.muted}>မတင်ရသေး</span>}</td><td data-label="Status"><span className={styles.status} data-status={row.payment_status}>{row.payment_status.replaceAll("_"," ")}</span></td><td data-label="လုပ်ဆောင်ရန်">{row.payment_status==="pending"?<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><form action={reviewCoachingPayment}><input type="hidden" name="registrationId" value={row.id}/><input type="hidden" name="decision" value="approve"/><button className={styles.button}>Approve</button></form><form action={reviewCoachingPayment}><input type="hidden" name="registrationId" value={row.id}/><input type="hidden" name="decision" value="reject"/><button className={styles.buttonSecondary}>Reject</button></form></div>:<span className={styles.muted}>{row.payment_status==="approved"?"Template ဆောက်ရန်":"ပြီးပါပြီ"}</span>}</td></tr>)}</tbody></table></div>:<div className={styles.empty}><strong>Payment မရှိသေးပါ</strong>Client က website မှာ screenshot တင်တာနဲ့ ဒီမှာပေါ်ပါမယ်။</div>}</section></>;
}
