-- Central Project Peak admin: Telegram OTP, one-device sessions, and audit trail.
-- Runtime access is service-role only. No browser key can read these tables.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.admin_otp_challenges (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null,
  request_fingerprint_hash text not null,
  telegram_delivery_count smallint not null default 0 check (telegram_delivery_count >= 0),
  attempts smallint not null default 0 check (attempts between 0 and 10),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint admin_otp_expiry_after_creation check (expires_at > created_at)
);

create index if not exists admin_otp_recent_request_idx
on public.admin_otp_challenges(request_fingerprint_hash, created_at desc);

create index if not exists admin_otp_expiry_idx
on public.admin_otp_challenges(expires_at)
where consumed_at is null;

create table if not exists public.admin_device_sessions (
  id uuid primary key default gen_random_uuid(),
  session_token_hash text not null unique,
  user_agent_hash text not null,
  last_ip_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  constraint admin_session_expiry_after_creation check (expires_at > created_at),
  constraint admin_session_revocation_state check (
    (active and revoked_at is null) or (not active and revoked_at is not null)
  )
);

create unique index if not exists admin_one_active_device_idx
on public.admin_device_sessions(active)
where active;

create index if not exists admin_session_lookup_idx
on public.admin_device_sessions(session_token_hash, active, expires_at);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_session_id uuid references public.admin_device_sessions(id) on delete set null,
  action text not null check (char_length(action) between 2 and 120),
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_created_idx
on public.admin_audit_log(created_at desc);

alter table public.admin_otp_challenges enable row level security;
alter table public.admin_device_sessions enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on table public.admin_otp_challenges from public, anon, authenticated;
revoke all on table public.admin_device_sessions from public, anon, authenticated;
revoke all on table public.admin_audit_log from public, anon, authenticated;
grant all on table public.admin_otp_challenges to service_role;
grant all on table public.admin_device_sessions to service_role;
grant all on table public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

-- Service-role requests are trusted server-to-server calls. This keeps the
-- original Google-auth admin behavior while allowing the isolated dashboard.
create or replace function private.is_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(current_setting('request.jwt.claim.role', true) = 'service_role', false)
    or (
      p_user_id is not null
      and exists (select 1 from private.admin_users a where a.user_id = p_user_id)
    );
$$;

revoke all on function private.is_admin(uuid) from public;
grant execute on function private.is_admin(uuid) to authenticated, service_role;
grant usage on schema private to authenticated, service_role;

create or replace function public.central_admin_actor_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select user_id from private.admin_users order by created_at asc limit 1;
$$;

revoke all on function public.central_admin_actor_id() from public, anon, authenticated;
grant execute on function public.central_admin_actor_id() to service_role;

create or replace function private.fill_service_reviewer()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.reviewer_id is null
     and current_setting('request.jwt.claim.role', true) = 'service_role' then
    select user_id into new.reviewer_id
    from private.admin_users
    order by created_at asc
    limit 1;
  end if;
  return new;
end;
$$;

drop trigger if exists payment_reviews_fill_service_reviewer on public.payment_reviews;
create trigger payment_reviews_fill_service_reviewer
before insert on public.payment_reviews
for each row execute function private.fill_service_reviewer();

create or replace function public.central_admin_activate_session(
  p_challenge_id uuid,
  p_session_token_hash text,
  p_user_agent_hash text,
  p_ip_hash text,
  p_expires_at timestamptz
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session_id uuid;
begin
  update public.admin_otp_challenges
  set consumed_at = now()
  where id = p_challenge_id
    and consumed_at is null
    and expires_at > now()
    and attempts < 5;

  if not found then
    raise exception 'OTP challenge is no longer valid' using errcode = '28000';
  end if;

  update public.admin_device_sessions
  set active = false, revoked_at = now()
  where active;

  insert into public.admin_device_sessions (
    session_token_hash, user_agent_hash, last_ip_hash, expires_at
  ) values (
    p_session_token_hash, p_user_agent_hash, p_ip_hash, p_expires_at
  ) returning id into v_session_id;

  insert into public.admin_audit_log (actor_session_id, action, entity_type, entity_id)
  values (v_session_id, 'auth.login.telegram_otp', 'admin_session', v_session_id::text);

  return v_session_id;
end;
$$;

revoke all on function public.central_admin_activate_session(uuid, text, text, text, timestamptz)
from public, anon, authenticated;
grant execute on function public.central_admin_activate_session(uuid, text, text, text, timestamptz)
to service_role;
